# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/142WmE5e3XxG0gb3mfixHh-SYRUxJ9M-4
"""

# pip install streamlit pymupdf transformers torch

import streamlit as st
import fitz
from transformers import pipeline
import numpy as np
import torch

from io import BytesIO

def extract_text_from_pdf(uploaded_file):
    text = ""
    pdf_document = fitz.open(stream=BytesIO(uploaded_file.read()), filetype="pdf")
    for page_num in range(pdf_document.page_count):
        page = pdf_document[page_num]
        text += page.get_text("text")
    return text

def answer_question(pdf_text, question):
    nlp_qa = pipeline("question-answering", model="distilbert-base-cased-distilled-squad")

    # Convert the list to a single numpy array
    input_ids = np.array(nlp_qa.tokenizer.encode(question, pdf_text))
    start_scores, end_scores = nlp_qa.model(torch.tensor([input_ids]))

    all_tokens = nlp_qa.tokenizer.convert_ids_to_tokens(input_ids)
    answer = nlp_qa.tokenizer.decode(input_ids[torch.argmax(start_scores): torch.argmax(end_scores) + 1])

    return answer

def main():
    st.title("PDF Question Answering App")

    uploaded_file = st.file_uploader("Choose a PDF file", type="pdf")

    if uploaded_file:
        pdf_text = extract_text_from_pdf(uploaded_file)

        st.subheader("PDF Content:")
        st.write(pdf_text)

        st.subheader("Ask Questions:")
        question = st.text_input("Type your question:")

        if st.button("Ask"):
            if not pdf_text:
                st.warning("Please upload a valid PDF file.")
            elif not question:
                st.warning("Please type a question.")
            else:
                # Convert the list to a single numpy array
                answer = answer_question(pdf_text, question)
                st.success(f"Answer: {answer}")

if __name__ == "__main__":
    main()




